### ISSUE TITLE
SD Card issues causing datakit to crash on start

### ISSUE THREAD

**Issue by twhnat** [MD2Korg/mCerebrum-DataKit#3]
I can't run the newest version of datakit on the phone to test the CerebralCortex interface.

     Caused by: java.lang.NullPointerException
            at org.md2k.datakit.manager.FileManager.getExternalSDCardDirectory(FileManager.java:90)
            at org.md2k.datakit.manager.FileManager.getValidSDcard(FileManager.java:147)
            at org.md2k.datakit.ActivityDataKit.updateSDCardSetttingsText(ActivityDataKit.java:70)
            at org.md2k.datakit.ActivityDataKit.onResume(ActivityDataKit.java:95)
            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1210)
            at android.app.Activity.performResume(Activity.java:5510)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2936)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2975)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2368)
            at android.app.ActivityThread.access$900(ActivityThread.java:161)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by monowar** [comment]
Bug fixed
